fix IDNCLOUD-295
wso2/carbon-appmgt pull request #664
Opened 2017-07-05 04:42 UTC by ayshsandu

Application redirects through gateway doesn't work properly with default versioned proxy type apps

2017-07-09 02:08 UTC, malithie requested changes

2017-07-09 02:08 UTC, malithie commented on components/org.wso2.carbon.appmgt.gateway/src/main/java/org/wso2/carbon/appmgt/gateway/handlers/proxy/ReverseProxyHandler.java
> +        int status = Integer.parseInt(String.valueOf(axis2MC.getProperty(NhttpConstants.HTTP_SC)));
Please fix formatting in this block

2017-07-11 04:13 UTC, ayshsandu commented on components/org.wso2.carbon.appmgt.gateway/src/main/java/org/wso2/carbon/appmgt/gateway/handlers/proxy/ReverseProxyHandler.java
> +        int status = Integer.parseInt(String.valueOf(axis2MC.getProperty(NhttpConstants.HTTP_SC)));
Done

2017-07-11 04:19 UTC, malithie approved these changes

2017-07-11 04:19 UTC, merged